// src/components/LibraryPanel.jsx
import React from 'react';
import { useStore } from '../store'; 
import '../pages/create.css';

export const LibraryPanel = ({ library, onAddModel, onClose }) => {
  // Get recommendations generated by Discover My Style
  const recommendedLibrary = useStore(state => state.recommendedLibrary);

  return (
    <div className="library-panel">
      <div className="library-header">
        <h3>Furniture Library</h3>
        <button onClick={onClose} className="close-button">✖</button>
      </div>

      <div className="library-content">

        {/* --- SECTION 1: SELECTED FOR YOU (Recommendations) --- */}
        {recommendedLibrary && recommendedLibrary.length > 0 && (
          <div className="library-section">
            <h4 className="section-title">✨ Selected For You</h4>

            <div className="library-grid">
              {recommendedLibrary.map(item => (
                <div 
                  key={`rec-${item.id}`} 
                  className="library-card recommended-card"
                >
                  <div className="card-badge">Match</div>

                  <img 
                    src={item.thumbnail_url} 
                    alt={item.name} 
                    className="library-thumbnail" 
                  />

                  <div className="library-card-footer">
                    <span className="library-item-name">{item.name}</span>
                    <button 
                      onClick={() => onAddModel(item)} 
                      className="add-button"
                    >
                      +
                    </button>
                  </div>
                </div>
              ))}
            </div>

            <hr className="library-divider" />
          </div>
        )}

        {/* --- SECTION 2: FULL CATALOG --- */}
        <div className="library-section">
          <h4 className="section-title">📚 Full Catalog</h4>

          <div className="library-grid">
            {library.map(item => (
              <div key={item.id} className="library-card">
                <img 
                  src={item.thumbnail_url} 
                  alt={item.name} 
                  className="library-thumbnail" 
                />

                <div className="library-card-footer">
                  <span className="library-item-name">{item.name}</span>
                  <button 
                    onClick={() => onAddModel(item)} 
                    className="add-button"
                  >
                    +
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>
    </div>
  );
};
